blog/urls.py
from django.urls import path, re_path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'blog'
urlpatterns = [
    path('blog/', views.home, name='home-blog'),
    #path('', views.MainView.as_view(), name='home-blog-view'),
    # path('posts-json/<int:num_posts>/',
    #      views.PostJsonListView.as_view(), name='posts-json-view'),
    # path('about/', views.about, name='about'),
    path('category/<str:slug>/', views.super_category, name='category'),
    # path('detail/<str:slug>', views.post_detail, name='postdetail'),
    re_path(r'^detail/(?P<slug>[^/]+)/?$',
            views.post_detail, name='postdetail'),
    # path('detail/<str:slug>/download/', views.post_detail, name='postdetail'),
    #url(r'tag/(?P<input_tag>\w+)$', views.tag_view, name='tag'),
    # path('new_post/', views.PostCreateView.as_view(), name='new_post'),
    # path('detail/<slug:pk>/update/',
    #      views.PostUpdateView.as_view(), name='update_post'),
    # path('detail/<slug:pk>/delete/',
    #      views.PostDeleteView.as_view(), name='delete_post'),


]
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import reverse_lazy


app_name = 'home'
urlpatterns = [
    path('', views.home_page, name='index'),
    path('set_currency/', views.set_currency , name='set-currency'),

]
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.views.static import serve
urlpatterns = [
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),

    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
    path('', include('home.urls', namespace='home')),
    path('', include('products.urls', namespace='products')),
    path('', include('accounts.urls', namespace='accounts')),
    path('', include('orders.urls', namespace='orders')),
    path('', include('categories.urls', namespace='categories')),
    path('', include('suppliers.urls', namespace='suppliers')),
    path('', include('supplier_panel.urls', namespace='supplier_dashboard')),
    path('', include('newsletters.urls', namespace='newsletters')),
    path('', include('blog.urls', namespace='blog')),
    path('', include('contact.urls', namespace='contact')),
    path('', include('pages.urls', namespace='pages')),
    path('currencies/', include('currencies.urls')),
    # url(r'^ads\.txt', include('ads_txt.urls')),

]
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _
from django.db.models.signals import pre_save
from .utils import code_generator, create_shortcode
from categories.models import SuperCategory
from ckeditor.fields import RichTextField
from accounts.models import Profile
# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=500)
    content = RichTextField(blank=True, null=True,
                            verbose_name=_("Content"))                      
    post_date = models.DateTimeField(default=timezone.now)
    post_update = models.DateTimeField(auto_now=True)
    post_supercategory = models.ForeignKey(
        SuperCategory, on_delete=models.SET_NULL, blank=True, null=True, verbose_name=_("Super Category"))
    author = models.ForeignKey(Profile, on_delete=models.CASCADE , related_name="author")
    # publisher = models.ForeignKey(
    #     User, on_delete=models.CASCADE, blank=True, null=True , related_name="publisher")
    post_image = models.ImageField(
        upload_to='blog/posts/', verbose_name=_("Post Image"), blank=True, null=True)
    views = models.IntegerField(default=0 ,  blank=True, null=True)    
    posttags = models.CharField(
        max_length=500, verbose_name=_("Tags"), blank=True, null=True)
    post_Slug = models.SlugField(max_length=500,
        blank=True, null=True, allow_unicode=True, unique=True, verbose_name=_("Slugfiy"))

    def __str__(self):

        return str(self.title)

    # def save(self, *args, **kwargs):
    #     if not self.post_Slug:
    #         self.post_Slug = slugify(self.title)
    #     super(Post, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:postdetail', kwargs={'slug': self.post_Slug})

    # def get_absolute_url(self):
    #     # return 'detail/{}'.format(self.pk)
    #     return reverse('blog:postdetail', args=[self.pk])

    class Meta:
        ordering = ('-post_date',)


def pre_save_post_receiver(sender, instance, *args, **kwargs):

    if not instance.post_Slug or instance.post_Slug is None or instance.post_Slug == "":
        instance.post_Slug = slugify(instance.title , allow_unicode=True)
        qs_exists = Post.objects.filter(post_Slug=instance.post_Slug).exists()
        if qs_exists:
            instance.post_Slug = create_shortcode(instance)


pre_save.connect(pre_save_post_receiver, sender=Post)


class Comment (models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    body = models.TextField(verbose_name='Enter Comment')
    comment_date = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='comments')
    profile = models.ForeignKey(
        Profile, on_delete=models.CASCADE, blank=True, null=True)    

    def __str__(self):
        return 'Commented {} on {}.'.format(self.name, self.post)

    class Meta:
        ordering = ('-comment_date',)




blog/views.py
from random import random
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
# from django.views.generic import CreateView, UpdateView, DeleteView, View, TemplateView
# from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
# from django.http import JsonResponse
from django.contrib import messages
from categories.models import SuperCategory
import datetime
from reports.models import PostReport, PostView
from django_user_agents.utils import get_user_agent
# import requests
from accounts.models import Profile
# Create your views here.


def get_ip(request):
    try:
        x_forward = request.META.get("HTTP_X_FORWARDED_FOR")
        if x_forward:
            ip=x_forward.split(",")[0]
        else:
            ip = request.META.get("REMOTE_ADDR")
    except:
        ip = ""

    return ip

def home(request):
    posts = Post.objects.all()
    paginator = Paginator(posts, 16)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_page)
    context = {
        'title': 'home page',
        'posts': posts,
        'page': page,

    }
    return render(request, 'blog/blog-fullwidth.html', context)



def super_category(request, slug):

    super_category_obj = SuperCategory.objects.get(slug=slug)
    posts = Post.objects.all().filter(post_supercategory = super_category_obj)
    paginator = Paginator(posts, 16)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_page)

    context = {
        "super_category_obj": super_category_obj,
        "slug": slug,
        'posts': posts,
        'page': page,

    }
    return render(request, "blog/blog-category-fullwidth.html", context)  


def post_detail(request, slug):
    post = get_object_or_404(Post, post_Slug=slug)
    random_posts = Post.objects.all().order_by("-post_date").order_by("?")[0:4]
    user_agent = get_user_agent(request)  
    try:

        view_report = PostView(post=post,
                            ip=get_ip(request),
                            created=datetime.date.today(),
                            session=request.session.session_key,
                            referral = request.META.get('HTTP_REFERER'),
                            user_agent = request.META['HTTP_USER_AGENT'] ,
                            user_agent_browser = user_agent.browser , 
                            user_agent_os =user_agent.os ,
                            user_agent_device = user_agent.device,
                            is_mobile = user_agent.is_mobile ,
                            is_tablet = user_agent.is_tablet,
                            is_touch_capable = user_agent.is_touch_capable,
                            is_pc = user_agent.is_pc,
                            is_bot = user_agent.is_bot,
                            )


        if not PostView.objects.filter(post=post,ip=get_ip(request)).exists() and user_agent.is_bot != True :

            post.views = post.views + 1
            post.save()
            view_report.save()

            try:
                post_report_obj = PostReport.objects.all().filter(created = datetime.date.today() ,post = post)
                
            except:
                post_report_obj = False 

            if post_report_obj :
                old_post_report = PostReport.objects.get(created = datetime.date.today(), post = post)
                old_post_report.impressions = old_post_report.impressions + 1
                #old_post_report.publisher = post.publisher
                old_post_report.save() 

            else:    
                post_report = PostReport(
                    impressions = 1,
                    created = datetime.date.today(),
                    post = post,
                    publisher = post.author,)
                post_report.save() 

                           
    except:
        pass

                  
    comments = post.comments.filter(active=True)
    print(comments)
    # check before save data from comment form
    if request.method == 'POST':
        if  request.user.is_authenticated and not request.user.is_anonymous:
            profile = Profile.objects.get(user = request.user)      
            name = request.POST['name']
            email = request.POST['email']
            comment = request.POST['comment']

            new_comment =  Comment(
                        name = name,
                        email =email,
                        body = comment,
                        post = post,
                        profile = profile)
            new_comment.save() 
            messages.success(
                request, f'Your comment has been sent')

        else:
             messages.warning(
                request, f'Please login to be able to comment')   
    
    context = {
        'post': post,
        'random_posts':random_posts,
        'comments': comments,
  
    }

    return render(request, 'blog/blog-post-fullwidth.html', context)
   

blog/templates/blog/blog-category-fullwidth.html
{% extends 'base.html' %}
{% load static %}

{%block body%}

<main class="main">
   <div class="page-header mt-30 mb-75">
       <div class="container">
           <div class="archive-header">
               <div class="row align-items-center">
                   <div class="col-xl-3">
                       <h1 class="mb-15">Blog & News</h1>
                       <div class="breadcrumb">
                           <a href="{%url 'home:index'%}" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                           <span></span> Blog & News
                       </div>
                   </div>
                   <!-- <div class="col-xl-9 text-end d-none d-xl-block">
                       <ul class="tags-list">
                           <li class="hover-up">
                               <a href="blog-category-grid.html"><i class="fi-rs-cross mr-10"></i>Shopping</a>
                           </li>
                           <li class="hover-up active">
                               <a href="blog-category-grid.html"><i class="fi-rs-cross mr-10"></i>Recips</a>
                           </li>
                           <li class="hover-up">
                               <a href="blog-category-grid.html"><i class="fi-rs-cross mr-10"></i>Kitchen</a>
                           </li>
                           <li class="hover-up">
                               <a href="blog-category-grid.html"><i class="fi-rs-cross mr-10"></i>News</a>
                           </li>
                           <li class="hover-up mr-0">
                               <a href="blog-category-grid.html"><i class="fi-rs-cross mr-10"></i>Food</a>
                           </li>
                       </ul>
                   </div> -->
               </div>
           </div>
       </div>
   </div>
   <div class="page-content mb-50">
       <div class="container">
           <div class="row">
               <div class="col-lg-12">
                   <!-- <div class="shop-product-fillter mb-50">
                       <div class="totall-product">
                           <h2>
                               <img class="w-36px mr-10" src="assets/imgs/theme/icons/category-1.svg" alt="" />
                               Recips Articles
                           </h2>
                       </div>
                       <div class="sort-by-product-area">
                           <div class="sort-by-cover mr-10">
                               <div class="sort-by-product-wrap">
                                   <div class="sort-by">
                                       <span><i class="fi-rs-apps"></i>Show:</span>
                                   </div>
                                   <div class="sort-by-dropdown-wrap">
                                       <span> 50 <i class="fi-rs-angle-small-down"></i></span>
                                   </div>
                               </div>
                               <div class="sort-by-dropdown">
                                   <ul>
                                       <li><a class="active" href="#">50</a></li>
                                       <li><a href="#">100</a></li>
                                       <li><a href="#">150</a></li>
                                       <li><a href="#">200</a></li>
                                       <li><a href="#">All</a></li>
                                   </ul>
                               </div>
                           </div>
                           <div class="sort-by-cover">
                               <div class="sort-by-product-wrap">
                                   <div class="sort-by">
                                       <span><i class="fi-rs-apps-sort"></i>Sort:</span>
                                   </div>
                                   <div class="sort-by-dropdown-wrap">
                                       <span>Featured <i class="fi-rs-angle-small-down"></i></span>
                                   </div>
                               </div>
                               <div class="sort-by-dropdown">
                                   <ul>
                                       <li><a class="active" href="#">Featured</a></li>
                                       <li><a href="#">Newest</a></li>
                                       <li><a href="#">Most comments</a></li>
                                       <li><a href="#">Release Date</a></li>
                                   </ul>
                               </div>
                           </div>
                       </div>
                   </div> -->
                   <div class="loop-grid">
                       <div class="row">
                           {% for post in posts%}
                           <article class="col-xl-3 col-lg-4 col-md-6 text-center hover-up mb-30 animated">
                               <div class="post-thumb">
                                   <a href="{%url 'blog:postdetail' post.post_Slug %}">
                                       <img class="border-radius-15" src="{{post.post_image.url}}" alt="" />
                                   </a>
                                   <!-- <div class="entry-meta">
                                       <a class="entry-meta meta-2" href="blog-category-grid.html"><i class="fi-rs-heart"></i></a>
                                   </div> -->
                               </div>
                               <div class="entry-content-2">
                                   <h6 class="mb-10 font-sm"><a class="entry-meta text-muted" href="{% url 'blog:category' post.post_supercategory.slug %}">{{post.post_supercategory}}</a></h6>
                                   <h4 class="post-title mb-15">
                                       <a href="{%url 'blog:postdetail' post.post_Slug %}">{{post.title|truncatechars:40}}</a>
                                   </h4>
                                   <div class="entry-meta font-xs color-grey mt-10 pb-10">
                                       <div>
                                           <span class="post-on mr-10"> {{post.post_date|date:"j F o"}}</span>
                                           <span class="hit-count has-dot mr-10">{{post.views}} Views</span>
                                           
                                       </div>
                                   </div>
                               </div>
                           </article>
                           {% endfor %}
                       </div>
                   </div>
                   {%if posts.has_other_pages %}
                   <div class="pagination-area mt-15 mb-sm-5 mb-lg-0">
                       <nav aria-label="Page navigation example">
                           <ul class="pagination justify-content-start">
                               {%if posts.has_previous%}
                               <li class="page-item">
                                   <a class="page-link" href="?page={{posts.previous_page_number}}"><i class="fi-rs-arrow-small-left"></i></a>
                               </li>
                               {%endif%}
                               <li class="page-item active"><a class="page-link" href="#">{{posts.number}}</a></li>
                               {%if posts.paginator.num_pages > postss.number  %}
                               
                               <li class="page-item"><a class="page-link" href="?page={{posts.number|add:1}}">{{posts.number|add:1}}</a></li>
                               {%endif%}
                                <!-- <li class="page-item"><a class="page-link" href="#">3</a></li> -->
                               <li class="page-item"><a class="page-link dot" href="#">...</a></li>
                               
                               <li class="page-item"><a class="page-link" href="?page={{posts.paginator.num_pages}}">{{posts.paginator.num_pages}}</a></li>
                               {%if posts.has_next%}
                               <li class="page-item">
                                   <a class="page-link" href="?page={{posts.next_page_number}}"><i class="fi-rs-arrow-small-right"></i></a>
                               </li>
                               {%endif%}
                           </ul>
                       </nav>
                   </div>
                   {%endif%} 
               </div>
           </div>
       </div>
   </div>
</main>

{%endblock body%}

blog/templates/blog/blog-fullwidth.html
 {% extends 'base.html' %}
 {% load static %}

 {%block body%}

 <main class="main">
    <div class="page-header mt-30 mb-75">
        <div class="container">
            <div class="archive-header">
                <div class="row align-items-center">
                    <div class="col-xl-3">
                        <h1 class="mb-15">Blog & News</h1>
                        <div class="breadcrumb">
                            <a href="{%url 'home:index'%}" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                            <span></span> Blog & News
                        </div>
                    </div>
                    <!-- <div class="col-xl-9 text-end d-none d-xl-block">
                        <ul class="tags-list">
                            <li class="hover-up">
                                <a href="blog-category-grid.html"><i class="fi-rs-cross mr-10"></i>Shopping</a>
                            </li>
                            <li class="hover-up active">
                                <a href="blog-category-grid.html"><i class="fi-rs-cross mr-10"></i>Recips</a>
                            </li>
                            <li class="hover-up">
                                <a href="blog-category-grid.html"><i class="fi-rs-cross mr-10"></i>Kitchen</a>
                            </li>
                            <li class="hover-up">
                                <a href="blog-category-grid.html"><i class="fi-rs-cross mr-10"></i>News</a>
                            </li>
                            <li class="hover-up mr-0">
                                <a href="blog-category-grid.html"><i class="fi-rs-cross mr-10"></i>Food</a>
                            </li>
                        </ul>
                    </div> -->
                </div>
            </div>
        </div>
    </div>
    <div class="page-content mb-50">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <!-- <div class="shop-product-fillter mb-50">
                        <div class="totall-product">
                            <h2>
                                <img class="w-36px mr-10" src="assets/imgs/theme/icons/category-1.svg" alt="" />
                                Recips Articles
                            </h2>
                        </div>
                        <div class="sort-by-product-area">
                            <div class="sort-by-cover mr-10">
                                <div class="sort-by-product-wrap">
                                    <div class="sort-by">
                                        <span><i class="fi-rs-apps"></i>Show:</span>
                                    </div>
                                    <div class="sort-by-dropdown-wrap">
                                        <span> 50 <i class="fi-rs-angle-small-down"></i></span>
                                    </div>
                                </div>
                                <div class="sort-by-dropdown">
                                    <ul>
                                        <li><a class="active" href="#">50</a></li>
                                        <li><a href="#">100</a></li>
                                        <li><a href="#">150</a></li>
                                        <li><a href="#">200</a></li>
                                        <li><a href="#">All</a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="sort-by-cover">
                                <div class="sort-by-product-wrap">
                                    <div class="sort-by">
                                        <span><i class="fi-rs-apps-sort"></i>Sort:</span>
                                    </div>
                                    <div class="sort-by-dropdown-wrap">
                                        <span>Featured <i class="fi-rs-angle-small-down"></i></span>
                                    </div>
                                </div>
                                <div class="sort-by-dropdown">
                                    <ul>
                                        <li><a class="active" href="#">Featured</a></li>
                                        <li><a href="#">Newest</a></li>
                                        <li><a href="#">Most comments</a></li>
                                        <li><a href="#">Release Date</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div> -->
                    <div class="loop-grid">
                        <div class="row">
                            {% for post in posts%}
                            <article class="col-xl-3 col-lg-4 col-md-6 text-center hover-up mb-30 animated">
                                <div class="post-thumb">
                                    <a href="{%url 'blog:postdetail' post.post_Slug %}">
                                        <img class="border-radius-15" src="{{post.post_image.url}}" alt="" />
                                    </a>
                                    <!-- <div class="entry-meta">
                                        <a class="entry-meta meta-2" href="blog-category-grid.html"><i class="fi-rs-heart"></i></a>
                                    </div> -->
                                </div>
                                <div class="entry-content-2">
                                    <h6 class="mb-10 font-sm"><a class="entry-meta text-muted" href="{% url 'blog:category' post.post_supercategory.slug %}">{{post.post_supercategory}}</a></h6>
                                    <h4 class="post-title mb-15">
                                        <a href="{%url 'blog:postdetail' post.post_Slug %}">{{post.title|truncatechars:40}}</a>
                                    </h4>
                                    <div class="entry-meta font-xs color-grey mt-10 pb-10">
                                        <div>
                                            <span class="post-on mr-10"> {{post.post_date|date:"j F o"}}</span>
                                            <span class="hit-count has-dot mr-10">{{post.views}} Views</span>
                                            
                                        </div>
                                    </div>
                                </div>
                            </article>
                            {% endfor %}
                        </div>
                    </div>
                    {%if posts.has_other_pages %}
                    <div class="pagination-area mt-15 mb-sm-5 mb-lg-0">
                        <nav aria-label="Page navigation example">
                            <ul class="pagination justify-content-start">
                                {%if posts.has_previous%}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{posts.previous_page_number}}"><i class="fi-rs-arrow-small-left"></i></a>
                                </li>
                                {%endif%}
                                <li class="page-item active"><a class="page-link" href="#">{{posts.number}}</a></li>
                                {%if posts.paginator.num_pages > posts.number  %}
                                
                                <li class="page-item"><a class="page-link" href="?page={{posts.number|add:1}}">{{posts.number|add:1}}</a></li>
                                {%endif%}
                                 <!-- <li class="page-item"><a class="page-link" href="#">3</a></li> -->
                                <li class="page-item"><a class="page-link dot" href="#">...</a></li>
                                
                                <li class="page-item"><a class="page-link" href="?page={{posts.paginator.num_pages}}">{{posts.paginator.num_pages}}</a></li>
                                {%if posts.has_next%}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{posts.next_page_number}}"><i class="fi-rs-arrow-small-right"></i></a>
                                </li>
                                {%endif%}
                            </ul>
                        </nav>
                    </div>
                    {%endif%} 
                </div>
            </div>
        </div>
    </div>
</main>

 {%endblock body%}