blog/urls.py
from django.urls import path, re_path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'blog'
urlpatterns = [
    path('blog/', views.home, name='home-blog'),
    #path('', views.MainView.as_view(), name='home-blog-view'),
    # path('posts-json/<int:num_posts>/',
    #      views.PostJsonListView.as_view(), name='posts-json-view'),
    # path('about/', views.about, name='about'),
    path('category/<str:slug>/', views.super_category, name='category'),
    # path('detail/<str:slug>', views.post_detail, name='postdetail'),
    re_path(r'^detail/(?P<slug>[^/]+)/?$',
            views.post_detail, name='postdetail'),
    # path('detail/<str:slug>/download/', views.post_detail, name='postdetail'),
    #url(r'tag/(?P<input_tag>\w+)$', views.tag_view, name='tag'),
    # path('new_post/', views.PostCreateView.as_view(), name='new_post'),
    # path('detail/<slug:pk>/update/',
    #      views.PostUpdateView.as_view(), name='update_post'),
    # path('detail/<slug:pk>/delete/',
    #      views.PostDeleteView.as_view(), name='delete_post'),


]
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'contact'
urlpatterns = [
    path('contact/', views.contact, name='contact'),
]
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.views.static import serve
urlpatterns = [
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),

    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
    path('', include('home.urls', namespace='home')),
    path('', include('products.urls', namespace='products')),
    path('', include('accounts.urls', namespace='accounts')),
    path('', include('orders.urls', namespace='orders')),
    path('', include('categories.urls', namespace='categories')),
    path('', include('suppliers.urls', namespace='suppliers')),
    path('', include('supplier_panel.urls', namespace='supplier_dashboard')),
    path('', include('newsletters.urls', namespace='newsletters')),
    path('', include('blog.urls', namespace='blog')),
    path('', include('contact.urls', namespace='contact')),
    path('', include('pages.urls', namespace='pages')),
    path('currencies/', include('currencies.urls')),
    # url(r'^ads\.txt', include('ads_txt.urls')),

]
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
# Create your models here.
class MessagesList (models.Model):
    name = models.CharField(max_length=150)
    email = models.EmailField()
    phone = models.CharField(max_length=50)
    subject = models.CharField(max_length=150)
    message = models.TextField()
    date = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    date_update = models.DateTimeField(auto_now=True, blank=True, null=True)

    class Meta:
        ordering = ('-id',)
            
        verbose_name = _("Message List")
        verbose_name_plural = _("Messages List")

    def __str__(self):
        return str(self.id)

contact/views.py
from django.shortcuts import render
from django.contrib import messages
from .models import MessagesList
# Create your views here.

def contact(request):

    if request.method == 'POST':
        try:
            name = request.POST['name']
            email = request.POST['email']
            phone = request.POST['phone']
            subject = request.POST['subject']
            message = request.POST['message']

            new_message =  MessagesList(
                        name = name,
                        email =email,
                        phone = phone,
                        subject = subject,
                        message = message)
            new_message.save() 
            messages.success(
                request, f'Your Message has been sent')   
        except:
            messages.warning(
                request, f'An unknown error occurred, please contact us in another way') 
    return render(request, 'contact/page-contact.html', )

contact/templates/contact/page-contact.html
{% extends 'base.html' %}
{% load static %}

{%block body%}

<main class="main pages">
    <div class="page-header breadcrumb-wrap">
        <div class="container">
            <div class="breadcrumb">
                <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                <span></span> Pages <span></span> Contact
            </div>
        </div>
    </div>
    <div class="page-content pt-50">
        
        <section class="container mb-50  d-md-block">
            <div class="border-radius-15 overflow-hidden">
                <iframe width="100%" height="500" src="https://maps.google.com/maps?q=new york, usa&t=&z=13&ie=UTF8&iwloc=&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe>
            </div>
        </section>
        <div class="container">
            <div class="row">
                <div class="col-xl-10 col-lg-12 m-auto">
                    <section class="mb-50">
                        <div class="row mb-60">
                            {%for info in contact_info|slice:":3"%}
                            <div class="col-md-4 mb-4 mb-md-0">
                                <h4 class="mb-15 text-brand">{{info.description}}</h4>
                                {{info.full_address|slice:"0:32"}}<br />
                                {{info.full_address|slice:"32:"}}<br />
                                <abbr title="Phone">Phone:</abbr> {{info.phone}}<br />
                                <abbr title="Email">Email: </abbr>{{info.email}}<br />
                                {%if info.map_link%}
                                <a href="{{info.map_link}}" class="btn btn-sm font-weight-bold text-white mt-20 border-radius-5 btn-shadow-brand hover-up"><i class="fi-rs-marker mr-5"></i>View map</a>
                                {%endif%}
                            </div>
                            {%endfor%}
                        </div>
                        <div class="row">
                            <div class="col-xl-8 col-lg-10 m-auto">
                                <div class="contact-from-area padding-20-row-col">
                                    {% if messages %}
                                    {% for message in messages %}
                      
                                    <div  id="message"  class="mt-30 alert align-middle alert-{{message.tags}}">
                                       
                                        <span class="align-middle"> {{message}}</span>
                                    </div>
                      
                                    {% endfor %}
                                    {% endif %}
                                    <h2 class="mb-10 text-center">Leave A Message</h2>
                                    <p class="text-muted  text-center mb-30 font-sm">Our staff will call back later and answer your questions.</p>
                                    <form class="contact-form-style mt-30" id="contact-form" method="POST" action="{%url 'contact:contact' %}">
                                        {% csrf_token %}
                                        <div class="row">
                                            <div class="col-lg-6 col-md-6">
                                                <div class="input-style mb-20">
                                                    <input name="name" placeholder="First Name" type="text" required/>
                                                </div>
                                            </div>
                                            <div class="col-lg-6 col-md-6">
                                                <div class="input-style mb-20">
                                                    <input name="email" placeholder="Your Email" type="email" required/>
                                                </div>
                                            </div>
                                            <div class="col-lg-6 col-md-6">
                                                <div class="input-style mb-20">
                                                    <input name="phone" placeholder="Your Phone" type="tel" required/>
                                                </div>
                                            </div>
                                            <div class="col-lg-6 col-md-6">
                                                <div class="input-style mb-20">
                                                    <input name="subject" placeholder="Subject" type="text" required/>
                                                </div>
                                            </div>
                                            <div class="col-lg-12 col-md-12">
                                                <div class="textarea-style mb-30">
                                                    <textarea name="message" placeholder="Message" required></textarea>
                                                </div>
                                                <button class="submit submit-auto-width" type="submit">Send message</button>
                                            </div>
                                        </div>
                                    </form>
                                    <p class="form-messege"></p>
                                </div>
                            </div>
                            
                        </div>
                    </section>
                </div>
            </div>
        </div>
    </div>
</main>

{%endblock body%}